### ISSUE TITLE
Analysis on different libfabric completion flags used by OpenFAM

### ISSUE THREAD

**Issue by soumya-pn** [OpenFAM/OpenFAM#117]
In OpenFAM we use FI_DELIVERY_COMPLETE along with libfabric operation. FI_COMMIT_COMPLETE is another experimental flag provided by libfabric, which is applied to operations that target persistent memory regions. Analyze which flag is best suited in case of persistent memory.

**Comment by mashoodk** [comment]
For now, we are not considering FI_COMMIT_COMPLETE as certain processor power features (ADR and eADR domain), makes sure the data cached in CPU caches or memory controllers will be flushed to pmem on power failure.
