### ISSUE TITLE
Linker warning on unresolved dependent library path while linking any application with OpenFAM

### ISSUE THREAD

**Issue by shomep** [OpenFAM/OpenFAM#153]
While linking any application with OpenFAM library we encounter the following warning message.
`ld: warning: libgpr.so.7, needed by //home/shome/GT/OpenFAM_2-0-1/OpenFAM/third-party/build/lib/libgrpc++.so.1, not found (try using -rpath or -rpath-link)`

On running an ldd on libgrpc++.so.1 this path shows as unresolved.
-bash-4.2$ ldd third-party/build/lib/libgrpc++.so
        linux-vdso.so.1 =>  (0x00007ffe8821f000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fcd37b9a000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fcd37992000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fcd37776000)
        libprofiler.so.0 => /lib64/libprofiler.so.0 (0x00007fcd37562000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fcd3734c000)
        libgrpc.so.7 => not found
        libgpr.so.7 => not found
        libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007fcd37044000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fcd36d42000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fcd36b2c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fcd3675e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fcd38027000)

As a workaround one needs to either provide the library path in the build instruction or set the LD_LIBRARY_PATH to point to the OpenFAM/third-party/build/lib directory.

**Comment by mashoodk** [comment]
Closing the issue for now. Application developers don't remember seeing this issue recently. If problem is seen again we will re-open.
