### ISSUE TITLE
Negative testcase: wrong IP address of CIS server in CMakeList.txt for CIS Server causing crash of application while CIS already started

### ISSUE THREAD

**Issue by rajakrishi** [OpenFAM/OpenFAM#162]
Ideally it should be gracefully exit. Need to be handled.

Steps:

- Start cis, Memory & metadata Server
- Provide wrong IP CIS IP address in OpenFAM/CmakeList.txt
- Run testcase

You see segfault and core will be generated for testcase: ~OpenFAM/build/test/reg-test/fam-api-reg/fam_put_get_reg_test

Reading symbols from /home/rajakr/2021/OpenFAM/build/test/reg-test/fam-api-reg/fam_put_get_reg_test...done.

warning: core file may not match specified executable file.
[New LWP 18294]
[New LWP 18295]

warning: .dynamic section for "/lib64/libkrb5.so.3" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libk5crypto.so.3" is not at the expected address (wrong library or version mismatch?)

warning: .dynamic section for "/lib64/libkrb5support.so.0" is not at the expected address (wrong library or version mismatch?)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `OpenFAM/build/./test/reg-test/fam-api-reg/fam_put_get_reg_tes'.
Program terminated with signal 11, Segmentation fault.
#0  openfam::Fam_Allocator_Client::create_region (this=0x0,
    name=name@entry=0x97c770 "test_0", nbytes=nbytes@entry=8192,
    permissions=permissions@entry=511, regionAttributes=regionAttributes@entry=0x0)
    at /home/rajakr/2021/OpenFAM/src/allocator/fam_allocator_client.cpp:102
102                                          regionAttributesParam, uid, gid);
Missing separate debuginfos, use: debuginfo-install glibc-2.17-307.el7.1.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.15.1-46.el7.x86_64 libcom_err-1.42.9-17.el7.x86_64 libevent-2.0.21-4.el7.x86_64 libgcc-4.8.5-39.el7.x86_64 libibverbs-22.4-4.el7_8.x86_64 libnl3-3.2.28-4.el7.x86_64 librdmacm-22.4-4.el7_8.x86_64 libselinux-2.5-15.el7.x86_64 libstdc++-4.8.5-39.el7.x86_64 numactl-libs-2.0.12-5.el7.x86_64 openssl-libs-1.0.2k-19.el7.x86_64 pcre-8.32-17.el7.x86_64 yaml-cpp-0.5.1-2.el7.x86_64 zlib-1.2.7-18.el7.x86_64
(gdb) bt
#0  openfam::Fam_Allocator_Client::create_region (this=0x0,
    name=name@entry=0x97c770 "test_0", nbytes=nbytes@entry=8192,
    permissions=permissions@entry=511, regionAttributes=regionAttributes@entry=0x0)
    at /home/rajakr/2021/OpenFAM/src/allocator/fam_allocator_client.cpp:102
#1  0x00007f54a1f55ee9 in openfam::fam::Impl_::fam_create_region (
    this=<optimized out>, name=name@entry=0x97c770 "test_0", size=size@entry=8192,
    permissions=permissions@entry=511, regionAttributes=regionAttributes@entry=0x0)
    at /home/rajakr/2021/OpenFAM/src/fam-api/fam.cpp:1155
#2  0x00007f54a1f6642e in openfam::fam::fam_create_region (this=<optimized out>,
    name=name@entry=0x97c770 "test_0", size=size@entry=8192,
    permissions=permissions@entry=511, regionAttributes=regionAttributes@entry=0x0)
    at /home/rajakr/2021/OpenFAM/src/fam-api/fam.cpp:3995
#3  0x000000000041b38c in FamPutGet_PutGetSuccess_Test::TestBody (this=<optimized out>)
    at /home/rajakr/2021/OpenFAM/test/reg-test/fam-api-reg/fam_put_get_reg_test.cpp:54
#4  0x00000000004482b3 in HandleSehExceptionsInMethodIfSupported<testing::Test, void> (
    location=0x44b6e0 "e test body", method=<optimized out>, object=<optimized out>)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2433
#5  testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (
    object=object@entry=0x97b870, method=<optimized out>,
    location=0x44b6e0 "e test body", location@entry=0x44b6de "the test body")
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2469
#6  0x00000000004362d0 in testing::Test::Run (this=this@entry=0x97b870)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2509
#7  0x00000000004363f1 in testing::TestInfo::Run (this=0x9253e0)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2684
#8  0x00000000004364b5 in testing::TestSuite::Run (this=0x925520)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2816
#9  0x000000000043f3e7 in testing::internal::UnitTestImpl::RunAllTests (
    this=this@entry=0x92f430)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:5338
#10 0x000000000043f58c in HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (location=<optimized out>, method=<optimized out>,
    object=<optimized out>)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2433
#11 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (
    location=0x44dd58 "auxiliary test code (environments or event listeners)",
    method=(bool (testing::internal::UnitTestImpl::*)(testing::internal::UnitTestImpl * const)) 0x43efc0 <testing::internal::UnitTestImpl::RunAllTests()>, object=0x92f430)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:2469
#12 testing::UnitTest::Run (this=<optimized out>)
    at /home/rajakr/2021/OpenFAM/third-party/googletest/src/gtest.cc:4928
#13 0x0000000000419d7d in RUN_ALL_TESTS ()
    at /home/rajakr/2021/OpenFAM/third-party/googletest/include/gtest/gtest.h:2473
#14 main (argc=1, argv=<optimized out>)
    at /home/rajakr/2021/OpenFAM/test/reg-test/fam-api-reg/fam_put_get_reg_test.cpp:91
(gdb)

**Comment by mashoodk** [comment]
We are not reading CIS address from CMakeList.txt. Now all the addresses are from config files. Closing the issue.
