### ISSUE TITLE
runtime cannot be set to NONE when using run_test.py

### ISSUE THREAD

**Issue by shomep** [OpenFAM/OpenFAM#198]
Currently we can set only PMIX and PMI2 as the "runtime" using the command line arguments to run_test.py. To set the runtime to NONE we need to modify the config/fam_pe_config.yaml after server startup.
We need to have an option of setting the "runtime" to NONE through command like argument as any change to the config/fam_pe_config.yaml is overwritten during openfam server startup.

**Comment by mashoodk** [comment]
Fixed in 3.0
