### ISSUE TITLE
Add C wrappers for OpenFAM API

### ISSUE THREAD

**Issue by mashoodk** [OpenFAM/OpenFAM#20]
For C Applications to access OpenFAM API, a C wrapper needs to be built. Further discussion needed to see if we should do it within OpenFAM.

**Comment by ssinghal53** [comment]
See https://github.com/OpenFAM/API/blob/master/fam.h as a starting point for this discussion. This is the original API that contained versions for C and C11 as well. I have added that to the API repository (which is historical at this point).

**Comment by mashoodk** [comment]
C wrappers are integrated with OpenFAM now.
