### ISSUE TITLE
Need to print more useful output from run_test.py

### ISSUE THREAD

**Issue by cynara-justine** [OpenFAM/OpenFAM#203]
Need to print more output from run_test.py
Currently it is difficult for a user to detect if a failure has occurred and if so why.
Useful information such as the following may be included:
1. created configuration file at : location
2. yamlonly option was specified, Generating yaml files.. exiting..

**Comment by mashoodk** [comment]
With introduction of openfam_adm, some of the above comments are fixed. Closing.
