### ISSUE TITLE
Audit use of EXPECT_STREQ() in tests

### ISSUE THREAD

**Issue by jlbyrne-hpe** [OpenFAM/OpenFAM#269]
EXPECT_STREQ() is meant to compare null-terminated C-strings. In fam_dataitem_interleave_test.cpp, it used to compare blocks of memory that have no terminating null and the comparison goes beyond the end of the buffer; in fam_region_registration_resize.cpp it is used to compare a block of memory that is assumed to be all nulls, which means only the first byte is actually checked.

**Comment by sriram-ravishankar** [comment]
Issue has been fixed as part of #275 and was merged with devel branch
