### ISSUE TITLE
fam_barrier_all issue in OpenFAM API

### ISSUE THREAD

**Issue by mseyedza** [OpenFAM/OpenFAM#54]
I am trying to use OpenFAM API in a simple FFT application below. I basically want to use fam_barrier_all() call to synchronize across processes that operate on the same dataset, but have an issue with doing so.

In my experiment, processes PE0 and PE1 map a data item ‘dataItemM’ in FAM to the virtual address space ‘M’ (Line 1) and then each PE uses half of the data item to update another data item called X (Line2). Line 3 is meant to suspend the execution of calling PEs and Line 4 prints all elements of the data item X.

The experiment shows that changes by PE1 in the data item ‘X’ are not transparent to PE0. Specifically, PE0 in Line 4 prints wrong values for modified elements by PE1.

However, if I add a delay (e.g., sleep(2)) between Line 3 and Line 4, PE0 can see all changes by PE1 in the data item X as intended.   
It seems that fam_barrier_all() does not suspend the execution of calling PE in Line 3 until the FAM accesses from all PEs are completed. Is it a behavior that is expected? 

********************************
1.	float *M = (float *) my_fam->fam_map(dataItemM);
float *X  = (float *) my_fam->fam_map(dataItemX);

2.	For(int i = 0; i < 1024; i++){
X[PE_ID*1024+i] = M[PE_ID*1024+i]*2;
}

3.	my_fam->fam_barrier_all();

4.	if(PE_ID==0){
For(int i = 0; i < 2048; i++){
cout << X[i] <<” ”;
}
}
********************************

**Comment by mashoodk** [comment]
Hello,

Fam_barrier_all() suppresses the execution of all the PE’s. It is a global barrier.
It uses PMIx_Fence to coordinate between different PE’s. 

We tried reproducing the behavior, but could not. Can you please provide below details :

1.	What are the options you have passed to fam_initialize ? 
In particular options “allocator” and “runtime”. 
2.	How were PE’s launched. Is it using mpirun or something like slurm ? 
Are you using mpirun and pmix from OpenFAM/third-party library. 
3.	Are the PE’s running on CPU’s which are cache coherent ? 
4.	What is the backing store (tmpfs or anything else) ?

**Comment by mseyedza** [comment]
Hello,

The options for "allocator" and "runtime" are "grpc" and "pmix", respectively. I'm using "mpirun" for lunching PE's from OpenFAM/third-party library. PE's running on CPU's should be cache coherent since I have not change any option related to the cache coherency.  For the backing store, I use the default version of the backing store.

Please let me know if you need more info.

**Comment by mashoodk** [comment]
fam_map is not supported on "grpc" allocator. You need to use allocator as "NVMM" (which mean shared memory ) to get fam_map to work. 

fam_map will throw following exception when "grpc" is used as allocator :
Error msg: fam_map is Not Yet Implemented for libfabric interface !!! 
Can you try with NVMM as allocator ?

**Comment by mseyedza** [comment]
I tried "NVMM" for the allocator. Please see the following message.
 
terminate called after throwing an instance of 'openfam::Fam_Allocator_Exception'
  what():  std::exception
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node nlmserver2 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
[1]+  Bus error               (core dumped) ../../../src/memoryserver -m 127.0.0.1

**Comment by mashoodk** [comment]
Ok. 
Is it feasible to remove /dev/shm/<user> and try again. 
Follow the below steps :
1.  To remove any instance of memory server running
pkill memoryserver 

2. remove contents of /dev/shm/<user>. You might see contents as below :
$ ls /dev/shm/abdulla
abdulla_NVMM_EPOCH  abdulla_NVMM_ROOT  abdulla_NVMM_Shelf_0_16  abdulla_NVMM_Shelf_16_0_1  abdulla_NVMM_Shelf_16_1_1

3. restart memory server. 
source setup.sh 127.0.0.1

4. Run program with "NVMM" as allocator.

**Comment by mashoodk** [comment]
Also is it possible to share a simple reproducer with us, we can run it and check.

**Comment by mseyedza** [comment]
Now, I can run with "NVMM" as allocator. However, still it generates non-deterministic outputs.

**Comment by mseyedza** [comment]
Sure, I will prepare a simple reproducer and share with you.

**Comment by mashoodk** [comment]
Discussed this over mail and fixed this issue by adding a fam_barrier_all() between initialization and usage of a dataitem. 
Initialization in PE1 was overwriting the dataitem updates by PE0. A wait till both PE's complete initialization fixed the issue.
