### ISSUE TITLE
The license file contains the wrong copyright notice

### ISSUE THREAD

**Issue by ssinghal53** [OpenFAM/OpenFAM#6]
The current license file states: "Copyright (c) 2019, OpenFAM"

This should be replaced by "(C) Copyright 2019, Hewlett Packard Enterprise Development LP."

**Comment by faizan-barmawer** [comment]
Sure, We will fix this.

In all our source files, the license text starts with this string:
"Copyright (c) 2019 Hewlett Packard Enterprise Development, LP."  
where "(c)" comes after "Copyright". 

Shall we retain the same text structure in the license file as well?

**Comment by ssinghal53** [comment]
Correct. The license text should start with "Copyright (c)". We need to replace "OpenFAM" with the correct legal entity. Dates should be either 2019 for files created last year, or 2020 for newly created files.
