### ISSUE TITLE
About provider setting

### ISSUE THREAD

**Issue by htjung94** [OpenFAM/OpenFAM#71]
If I want to use rdma instead of socket as a provider, how do I set the provider?

**Comment by faizan-barmawer** [comment]
Please refer OpenFAM API documentation for fam_initialize API - https://openfam.github.io/fam_initialize.html
Use "libfabricProvider" option to select the underlying libfabric provider types use rdma. Supported option values are "sockets", "psm2" and "verbs".

**Comment by mashoodk** [comment]
Hello @htjung94 were you able get OpenFAM working with other providers ?

**Comment by mashoodk** [comment]
Closing this issue. Please open a new issue in case you have more queries.
