### ISSUE TITLE
Please add the input data of pagerank test

### ISSUE THREAD

**Issue by giocafe** [OpenFAM/OpenFAM#77]
I want to test the pagerank application.
But there is a config file, no input file.

And in config file context, input file path is invalid.
- /home/abdulla/work/OpenFAM_SpMV/graph500/src/out_20_4_8

Please add the input data of pagerank test and correct the path in config file.
Thanks.

**Comment by mashoodk** [comment]
Pagerank can be run using two types of input, Parmat format and format based on Graph500 input. 

We would recommend you to use parmat based format : 

To run those :
#PARMAT Input

Location of parmat : 
https://github.com/farkhor/PaRMAT

Parmat command to generate matrix of size 1M x 1M with 4 non zero per row
./PaRMAT -nVertices 1048576 -nEdges 1048576*4 -sorted

Load data to FAM
../third-party/build/bin/mpirun -np 1 ./test/apps/pagerank/fam_csr_preload_parmat parmat_1M_4M.txt 1048576 4

Pagerank with rows per itertion 1k and number of iterations 5
../third-party/build/bin/mpirun -np 8 ./test/apps/pagerank/fam_pagerank_parmat 1024 5

Let us know if you face any other issues.

**Comment by giocafe** [comment]
Thank for replying :-)

It's a slightly different question,
When will the load/store interface be available between compute server and memory server?
For example, fam_map/fam_unmap in grpc.
The purpose of OpenFAM is to make the large-scale shared memory pool using a memory semantic interface, isn't it?

**Comment by giocafe** [comment]
Where is the input file "parmat_1M_4M.txt"???

**Comment by mashoodk** [comment]
input file needs to be created using 
./PaRMAT -nVertices 1048576 -nEdges 1048576*4 -sorted

**Comment by giocafe** [comment]
Yes, I did.
The result is printed as below.
--
root@vm2-Standard-PC-Q35-ICH9-2009:~/OpenFAM/OpenFAM/test/apps/pagerank/PaRMAT/Release
$ ./PaRMAT -nVertices 1048576 -nEdges 1048576*4 -sorted
Requested graph will have 1048576 edges and 1048576 vertices.
Its a, b, and c parameters will be respectively 0.45, 0.22, and 0.22.
There can be up to 15 worker CPU thread(s) making the graph.
The graph will necessarily be sorted.
Up to about 50 percent of RAM can be used by this program.
Specified graph may contain edges that have same source and destination index.
Specified graph may contain duplicate edges.
Specified graph will be DIRECTED.
Each thread capacity is 219788373 edges.
16 rectangle(s) specified.
Generating the graph ...
||||||||||||||||
Done.
--
But, the file isn't generated.

**Comment by mashoodk** [comment]
You might need to use : or checkout out.txt 
	-Output file (default: out.txt). E.g., -output myout.txt

**Comment by giocafe** [comment]
What a beautiful, I love it!
Thank you for your advice.
![image](https://user-images.githubusercontent.com/9820744/93456164-4592c780-f918-11ea-9b70-85bdc2c2b3f0.png)

p.s.
If you have time, please answer any of the above questions.
If you have any questions in my question, feel free to ask.

When will the load/store interface be available between compute server and memory server?
For example, fam_map/fam_unmap in grpc.
The purpose of OpenFAM is to make the large-scale shared memory pool using a memory semantic interface, isn't it?

**Comment by mashoodk** [comment]
>> When will the load/store interface be available between compute server and memory server?
>> For example, fam_map/fam_unmap in grpc.
>> The purpose of OpenFAM is to make the large-scale shared memory pool using a memory semantic interface, isn't it?
We shall reply to you tomorrow on this.

**Comment by mashoodk** [comment]
OpenFAM runs in two modes - Shared memory model and memory server model. In shared memory model the clients have direct access to the FAM (Load store semantic). Shared memory model currently supports fam_map and fam_unmap.  In memory server model the clients connect to memory server via libfabric. The data transfer in this mode is via fabric providers like Infiniband, Omnipath and socket providers (and slingshot in future). None of these providers currently support load store semantic. They support put get semantic. So in order to test fam_map and fam_unmap we will need to use shared_memory model.

**Comment by giocafe** [comment]
I meant "Memory Server Model" in my question.
Do you have a plan which supports load/store semantic in Memory Server Model?
If so, when does it become possible?

And I have another question.
What you meant "Shared Memory Model" is, do you mean communicating only within localhost?

**Comment by mashoodk** [comment]
>> Do you have a plan which supports memory(load/store) semantic in Memory Server Model?
>> If so, when does it become possible?
Not at the moment. We need to have libfabric support load-store semantics to do that.

>> What you meant "Shared Memory Model" is, do you mean communicating only within localhost?
In shared memory model, the memory and compute node should be in the same system.

>> Memory Server Model : use GRPC Allocator
>> Shared Memory Model : use NVMM Allocator
Yes it is right.

**Comment by mashoodk** [comment]
Closing this issue. Please open a new issue in case you have more queries.
