### ISSUE TITLE
For "all rpc" config, fam_mm_reg_test fails to create region

### ISSUE THREAD

**Issue by rajakrishi** [OpenFAM/OpenFAM#98]
While running regression tests fam_mm_reg_test fails. Attached below are log and crash dump.

=============================================================
 30/43 Testing: fam_mm_reg_test
 30/43 Test: fam_mm_reg_test
 Command: "/home/rajakr/development/openfam-devel/run_test.sh" "/home/rajakr/development/openfam-devel/build/test/reg-test/fam-api-reg/fam_mm_reg_test"
 Directory: /home/rajakr/development/openfam-devel/build/test/reg-test/fam-api-reg
 "fam_mm_reg_test" start time: Nov 16 20:39 PST
 Output:
 ----------------------------------------------------------
 ^[[0;32m[==========] ^[[mRunning 12 tests from 2 test suites.
 ^[[0;32m[----------] ^[[mGlobal test environment set-up.
 ^[[0;32m[----------] ^[[m11 tests from FamMMTest
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamCreateDestroySuccess
 ^[[0;32m[       OK ] ^[[mFamMMTest.FamCreateDestroySuccess (356 ms)
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamAllocateDeallocateSuccess
 ^[[0;32m[       OK ] ^[[mFamMMTest.FamAllocateDeallocateSuccess (357 ms)
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamAllocateDeallocateBignameSuccess
 ^[[0;32m[       OK ] ^[[mFamMMTest.FamAllocateDeallocateBignameSuccess (356 ms)
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamAllocateSameSuccess
 ^[[0;32m[       OK ] ^[[mFamMMTest.FamAllocateSameSuccess (357 ms)
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamCheckPermissionSuccess
 ^[[0;32m[       OK ] ^[[mFamMMTest.FamCheckPermissionSuccess (356 ms)
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamCreateSameRegionDestroysSuccess
 ^[[0;32m[       OK ] ^[[mFamMMTest.FamCreateSameRegionDestroysSuccess (357 ms)
 ^[[0;32m[ RUN      ] ^[[mFamMMTest.FamAllocateMultipleItemsSameHeapSuccess
 /home/rajakr/development/openfam-devel/test/reg-test/fam-api-reg/fam_mm_reg_test.cpp:183: Failure
 Expected: desc = my_fam->fam_create_region(testRegion, 2147483648, 0777, RAID1) doesn't throw an exception.
   Actual: it throws.
 /home/rajakr/development/openfam-devel/test/reg-test/fam-api-reg/fam_mm_reg_test.cpp:184: Failure
 Expected: ((void *)__null) != (desc), actual: NULL vs NULL
 --------------------------------------------------------------------------
 Primary job  terminated normally, but 1 process returned
 a non-zero exit code. Per user-direction, the job has been aborted.
 --------------------------------------------------------------------------
 --------------------------------------------------------------------------
 mpirun noticed that process rank 0 with PID 0 on node drogon-1-ch3 exited on signal 11 (Segmentation fault).
 --------------------------------------------------------------------------
 <end of output>
 Test time =   4.61 sec
 ----------------------------------------------------------
 Test Failed.
 "fam_mm_reg_test" end time: Nov 16 20:39 PST
 "fam_mm_reg_test" time elapsed: 00:00:04
 ----------------------------------------------------------

==============================================

rajakr@drogon-1-ch3:~/development/openfam-devel/build$ gdb /home/rajakr/development/openfam-devel/build/test/reg-test/fam-api-reg/fam_mm_reg_test ./test/reg-test/fam-api-reg/core
GNU gdb (Ubuntu 8.1-0ubuntu3.2) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /home/rajakr/development/openfam-devel/build/test/reg-test/fam-api-reg/fam_mm_reg_test...done.
[New LWP 89263]
[New LWP 89264]
[New LWP 89265]
[New LWP 89273]
[New LWP 89266]
[New LWP 89268]
[New LWP 89269]
[New LWP 89270]
[New LWP 89267]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `/home/rajakr/development/openfam-devel/build/test/reg-test/fam-api-reg/fam_mm_r'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  openfam::Fam_Region_Descriptor::get_global_descriptor (this=this@entry=0x0) at /home/rajakr/development/openfam-devel/src/fam-api/fam_descriptor.cpp:309
309         return frdimpl_->get_global_descriptor();
[Current thread is 1 (Thread 0x7f06b03d88c0 (LWP 89263))]
(gdb) bt
#0  openfam::Fam_Region_Descriptor::get_global_descriptor (this=this@entry=0x0) at /home/rajakr/development/openfam-devel/src/fam-api/fam_descriptor.cpp:309
#1  0x00007f06aff0691e in openfam::Fam_Allocator_Client::allocate (this=0x5654514ca790, name=0x7ffc2e8ddad0 "test1589756693", nbytes=1024,
    accessPermissions=292, region=0x0) at /home/rajakr/development/openfam-devel/src/allocator/fam_allocator_client.cpp:108
#2  0x00007f06afec93d9 in openfam::fam::Impl_::fam_allocate (this=<optimized out>, name=<optimized out>, nbytes=<optimized out>,
    accessPermissions=<optimized out>, region=<optimized out>) at /home/rajakr/development/openfam-devel/src/fam-api/fam.cpp:1192
#3  0x00007f06afecff6e in openfam::fam::fam_allocate (this=<optimized out>, name=<optimized out>, nbytes=<optimized out>,
    accessPermissions=<optimized out>, region=<optimized out>) at /home/rajakr/development/openfam-devel/src/fam-api/fam.cpp:3910
#4  0x00005654508c4170 in FamMMTest_FamAllocateMultipleItemsSameHeapSuccess_Test::TestBody (this=<optimized out>)
    at /home/rajakr/development/openfam-devel/test/reg-test/fam-api-reg/fam_mm_reg_test.cpp:187
#5  0x00005654508f22fa in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void> (location=0x5654508f5416 "the test body",
    method=<optimized out>, object=0x565451485760) at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2433
#6  testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void> (object=object@entry=0x565451485760, method=<optimized out>,
    location=location@entry=0x5654508f5416 "the test body") at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2469
#7  0x00005654508e76d3 in testing::Test::Run (this=0x565451485760) at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2508
#8  0x00005654508e7835 in testing::TestInfo::Run (this=0x56545148e010) at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2684
#9  0x00005654508e7915 in testing::TestSuite::Run (this=0x5654514890e0) at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2816
#10 0x00005654508e7e38 in testing::internal::UnitTestImpl::RunAllTests (this=<optimized out>)
    at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:5338
#11 0x00005654508f280a in testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (
    location=0x5654508f6820 "auxiliary test code (environments or event listeners)", method=<optimized out>, object=0x5654514803e0)
    at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2433
#12 testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (object=0x5654514803e0, method=<optimized out>,
    location=location@entry=0x5654508f6820 "auxiliary test code (environments or event listeners)")
    at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:2469
#13 0x00005654508e8048 in testing::UnitTest::Run (this=0x565450b08520 <testing::UnitTest::GetInstance()::instance>)
    at /home/rajakr/development/openfam-devel/third-party/googletest/src/gtest.cc:4925
#14 0x00005654508bedc5 in RUN_ALL_TESTS () at /home/rajakr/development/openfam-devel/third-party/googletest/include/gtest/gtest.h:2473
#15 main (argc=<optimized out>, argv=<optimized out>) at /home/rajakr/development/openfam-devel/test/reg-test/fam-api-reg/fam_mm_reg_test.cpp:284
(gdb)

====================================

**Comment by mashoodk** [comment]
This failure is not seen with OpenFAM 3.0. Closing.
